version: '3.8'

services:
  mongo:
    image: mongo:latest
    hostname: foover-db
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: